### ISSUE TITLE
Property not defined in the class

### ISSUE THREAD

**Issue by sergii-zheleznytskyi** [lsretailomni/lsmag-two#34]
The property ` $this->data`is not defined and looks like its suppose to be 
`$this->helper->` instead
https://github.com/lsretailomni/lsmag-two/blob/ccac56562b89195761f0397dbd40c4ce735f56c7/src/Replication/Cron/SyncOrders.php#L152

**Comment by lsretailomni** [comment]
Hi @sergii-zheleznytskyi ,

Thanks for reporting, it seems to be this has already being fixed in the latest branch, please see below file for reference: https://github.com/lsretailomni/lsmag-two/blob/master/src/Replication/Cron/SyncOrders.php

Please make sure you are using the latest package(v1.8.0) from the github.
