### ISSUE TITLE
Missing functionality to update product category 

### ISSUE THREAD

**Issue by bmxmiwe** [lsretailomni/lsmag-two#48]
### Preconditions (*)
1. Magento version: 2.4.5 p4
2. LS eCommerce Magento version - 2.3.0
3. LS Retail Partner - Hagar

### Steps to reproduce (*)
1. Change product category in BC
2. Wait some time for executing all crons

### Expected result (*)
1. Product should be moved to new product category.

### Actual result (*)
1. Nothing happens, if You want to move product to another category, You must delete product in magento and import again or do it manually in Magento

**Comment by umarusaf902** [comment]
Hi @bmxmiwe,
Thanks for reporting this issue. We have tried to repeat the same process but unfortunately its not reproduce able. Once you update the product category/hierarchy leaf in BC, are you getting the delta updates in table `ls_replication_repl_hierarchy_leaf`. If yes, what happens when you try to run cron `repl_item_updates_sync` manually ? Can you record a video showing all this process ?

**Comment by umarusaf902** [comment]
Hi @bmxmiwe, Following up on this.

**Comment by umarusaf902** [comment]
Closing this issue as resolved since no response is received.
